---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cstor-1r
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
parameters:
  cas-type: cstor
  replicaCount: "1"
  cstorPoolCluster: cstorpool-yoqwl

